pipeline {
    agent any

    environment {
        IMAGE_NAME = 'rohanvasista/node-docker-ci'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Rohanvasista/node-docker-ci.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-creds', url: 'https://hub.docker.com/repositories/rohanvasista']) {
                    script {
                        docker.image("${IMAGE_NAME}").push("latest")
                    }
                }
            }
        }
    }
}
